# ---------------------------------------------------------------------------
# calcField_python.py
# Created on: 2013-05-21 08:14:09.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
CntyMilesTable20130521_dbf = "C:\\TxDOT\\Scratch\\CntyMilesTable20130521.dbf"

# Process: Calculate Field
arcpy.CalculateField_management(CntyMilesTable20130521_dbf, "TotalMiles", "!SUM_LEN_OF!", "PYTHON_9.3", "")

