# ---------------------------------------------------------------------------
# EventsLayer.py
# Created on: 2013-05-21 12:09:49.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
TXDOT_Roadways = "TXDOT_Roadways"
TPP_GIS_MCHAMB1_SUBFILES = "TPP_GIS.MCHAMB1.SUBFILES"
RDWY_Events = "RDWY_Events"

# Process: Make Route Event Layer
arcpy.MakeRouteEventLayer_lr(TXDOT_Roadways, "RTE_ID", TPP_GIS_MCHAMB1_SUBFILES, "RTE_ID LINE BMP EMP", RDWY_Events, "", "NO_ERROR_FIELD", "NO_ANGLE_FIELD", "NORMAL", "ANGLE", "LEFT", "POINT")

