# ---------------------------------------------------------------------------
# Truncate_RDC.py
# Created on: 2012-02-03 16:03:15.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy, datetime

print "Begin: " + str(datetime.datetime.now().time())

# Local variables:
#Centerline = "\\\\txapp39\\arcgisserver\\TPP\\TPP_DB.gdb\\WGS84_RDC\\Centerline"
#Intersections = "\\\\txapp39\\arcgisserver\\TPP\\TPP_DB.gdb\\WGS84_RDC\\Intersections"
#Line_Elements = "\\\\txapp39\\arcgisserver\\TPP\\TPP_DB.gdb\\WGS84_RDC\\Line_Elements"
#Markers = "\\\\txapp39\\arcgisserver\\TPP\\TPP_DB.gdb\\WGS84_RDC\\Markers"
#Monuments = "\\\\txapp39\\arcgisserver\\TPP\\TPP_DB.gdb\\WGS84_RDC\\Monuments"
#Point_Elements = "\\\\txapp39\\arcgisserver\\TPP\\TPP_DB.gdb\\WGS84_RDC\\Point_Elements"
#Termini = "\\\\txapp39\\arcgisserver\\TPP\\TPP_DB.gdb\\WGS84_RDC\\Termini"

Centerline = "\\\\tsd-gisgpc-3\\TPP\\TPP_DB.gdb\\WGS84_RDC\\Centerline"
Intersections = "\\\\tsd-gisgpc-3\\TPP\\TPP_DB.gdb\\WGS84_RDC\\Intersections"
Line_Elements = "\\\\tsd-gisgpc-3\\TPP\\TPP_DB.gdb\\WGS84_RDC\\Line_Elements"
Markers = "\\\\tsd-gisgpc-3\\TPP\\TPP_DB.gdb\\WGS84_RDC\\Markers"
Monuments = "\\\\tsd-gisgpc-3\\TPP\\TPP_DB.gdb\\WGS84_RDC\\Monuments"
Point_Elements = "\\\\tsd-gisgpc-3\\TPP\\TPP_DB.gdb\\WGS84_RDC\\Point_Elements"
Termini = "\\\\tsd-gisgpc-3\\TPP\\TPP_DB.gdb\\WGS84_RDC\\Termini"

# Process: Delete Features
print "Truncating Centerline..."
arcpy.DeleteFeatures_management(Centerline)

# Process: Delete Features (2)
print "Truncating Intersections..."
arcpy.DeleteFeatures_management(Intersections)

# Process: Delete Features (3)
print "Truncating Line_Elements..."
arcpy.DeleteFeatures_management(Line_Elements)

# Process: Delete Features (4)
print "Truncating Markers..."
arcpy.DeleteFeatures_management(Markers)

# Process: Delete Features (5)
print "Truncating Monuments..."
arcpy.DeleteFeatures_management(Monuments)

# Process: Delete Features (6)
print "Truncating Point_Elements..."
arcpy.DeleteFeatures_management(Point_Elements)

# Process: Delete Features (7)
print "Truncating Termini..."
arcpy.DeleteFeatures_management(Termini)

print "End: " + str(datetime.datetime.now().time())

