# ---------------------------------------------------------------------------
# Append_RDC.py
# Created on: 2012-02-03 16:10:38.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy, datetime

print "Begin: " + str(datetime.datetime.now().time())

# Local variables:
TPP_GIS_MCHAMB1_Centerline = "Database Connections\\Comanche.sde\\TPP_GIS.MCHAMB1.Regional_Data_Collection\\TPP_GIS.MCHAMB1.Centerline"
TPP_GIS_MCHAMB1_Intersections = "Database Connections\\Comanche.sde\\TPP_GIS.MCHAMB1.Regional_Data_Collection\\TPP_GIS.MCHAMB1.Intersections"
TPP_GIS_MCHAMB1_Line_Elements = "Database Connections\\Comanche.sde\\TPP_GIS.MCHAMB1.Regional_Data_Collection\\TPP_GIS.MCHAMB1.Line_Elements"
TPP_GIS_MCHAMB1_Markers = "Database Connections\\Comanche.sde\\TPP_GIS.MCHAMB1.Regional_Data_Collection\\TPP_GIS.MCHAMB1.Markers"
TPP_GIS_MCHAMB1_Monuments = "Database Connections\\Comanche.sde\\TPP_GIS.MCHAMB1.Regional_Data_Collection\\TPP_GIS.MCHAMB1.Monuments"
TPP_GIS_MCHAMB1_Point_Elements = "Database Connections\\Comanche.sde\\TPP_GIS.MCHAMB1.Regional_Data_Collection\\TPP_GIS.MCHAMB1.Point_Elements"
TPP_GIS_MCHAMB1_Termini = "Database Connections\\Comanche.sde\\TPP_GIS.MCHAMB1.Regional_Data_Collection\\TPP_GIS.MCHAMB1.Termini"
Termini__2_ = "\\\\tsd-gisgpc-3\\TPP\\TPP_DB.gdb\\WGS84_RDC\\Termini"
Point_Elements__2_ = "\\\\tsd-gisgpc-3\\TPP\\TPP_DB.gdb\\WGS84_RDC\\Point_Elements"
Monuments__2_ = "\\\\tsd-gisgpc-3\\TPP\\TPP_DB.gdb\\WGS84_RDC\\Monuments"
Markers__2_ = "\\\\tsd-gisgpc-3\\TPP\\TPP_DB.gdb\\WGS84_RDC\\Markers"
Line_Elements__2_ = "\\\\tsd-gisgpc-3\\TPP\\TPP_DB.gdb\\WGS84_RDC\\Line_Elements"
Intersections__2_ = "\\\\tsd-gisgpc-3\\TPP\\TPP_DB.gdb\\WGS84_RDC\\Intersections"
Centerline__2_ = "\\\\tsd-gisgpc-3\\TPP\\TPP_DB.gdb\\WGS84_RDC\\Centerline"

# Process: Append
print "Appending Termini..."
arcpy.Append_management("'Database Connections\\Comanche.sde\\TPP_GIS.MCHAMB1.Regional_Data_Collection\\TPP_GIS.MCHAMB1.Termini'", Termini__2_, "TEST", "", "")

# Process: Append (2)
print "Appending Point Elements..."
arcpy.Append_management("'Database Connections\\Comanche.sde\\TPP_GIS.MCHAMB1.Regional_Data_Collection\\TPP_GIS.MCHAMB1.Point_Elements'", Point_Elements__2_, "TEST", "", "")

# Process: Append (3)
print "Appending Monuments..."
arcpy.Append_management("'Database Connections\\Comanche.sde\\TPP_GIS.MCHAMB1.Regional_Data_Collection\\TPP_GIS.MCHAMB1.Monuments'", Monuments__2_, "TEST", "", "")

# Process: Append (4)
print "Appending Markers..."
arcpy.Append_management("'Database Connections\\Comanche.sde\\TPP_GIS.MCHAMB1.Regional_Data_Collection\\TPP_GIS.MCHAMB1.Markers'", Markers__2_, "TEST", "", "")

# Process: Append (5)
print "Appending Line Elements..."
arcpy.Append_management("'Database Connections\\Comanche.sde\\TPP_GIS.MCHAMB1.Regional_Data_Collection\\TPP_GIS.MCHAMB1.Line_Elements'", Line_Elements__2_, "TEST", "", "")

# Process: Append (6)
print "Appending Intersections..."
arcpy.Append_management("'Database Connections\\Comanche.sde\\TPP_GIS.MCHAMB1.Regional_Data_Collection\\TPP_GIS.MCHAMB1.Intersections'", Intersections__2_, "TEST", "", "")

# Process: Append (7)
print "Appending Centerline..."
arcpy.Append_management("'Database Connections\\Comanche.sde\\TPP_GIS.MCHAMB1.Regional_Data_Collection\\TPP_GIS.MCHAMB1.Centerline'", Centerline__2_, "TEST", "", "")

print "End: " + str(datetime.datetime.now().time())