# ---------------------------------------------------------------------------
# RDC_UpdateTiles.pye
# Created on: 2012-02-17 16:41:30.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy, datetime

print "Begin: " + str(datetime.datetime.now().time())

# Process: Manage Map Server Cache Tiles
print "Re-creating Regional Data Collection map cache..."
#arcpy.ManageMapServerCacheTiles_server("txapp39", "TPP/RegionalDataCollection_WM", "Layers", "'Regional Data Collection';'TPP Centerline';District;County;City_Polygon;District", "9244648.868618;4622324.434309;2311162.217155;1155581.108577;577790.554289;288895.277144;144447.638572;72223.819286;36111.909643;18055.954822", "Recreate All Tiles", "-11871802.9060954 2978933.87133157 -10409240.680754 4369723.28731712", "2", "NONE", "", "IGNORE_COMPLETION_STATUS_FIELD")
arcpy.ManageMapServerCacheTiles_server("tsd-gisgpc-3", "TPP/RegionalDataCollection_WM", "Layers", "'Regional Data Collection';'TPP Centerline';District;County;City_Polygon;District", "9244648.868618;4622324.434309;2311162.217155;1155581.108577;577790.554289;288895.277144;144447.638572;72223.819286;36111.909643;18055.954822", "Recreate All Tiles", "-11871802.9060954 2978933.87133157 -10409240.680754 4369723.28731712", "2", "NONE", "", "IGNORE_COMPLETION_STATUS_FIELD")

print "End: " + str(datetime.datetime.now().time())
