# ---------------------------------------------------------------------------
# CalcField_String.py
# Created on: 2013-05-20 10:49:45.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
District_Offices_shp__2_ = "C:\\TxDOT\\Shapefiles\\District_Offices.shp"

# Process: Calculate Field
arcpy.CalculateField_management(District_Offices_shp__2_, "State", "\"Texas\"", "VB", "")

