# ---------------------------------------------------------------------------
# parameters.py
# Created on: 2013-05-21 09:23:02.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: parameters <Output_data_element> <Input_Data_Element> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
Output_data_element = arcpy.GetParameterAsText(0)

Input_Data_Element = arcpy.GetParameterAsText(1)

# Local variables:

# Process: Copy
arcpy.Copy_management(Input_Data_Element, Output_data_element, "")

