# ---------------------------------------------------------------------------
# XLSXtoDBF.py
# Created on: 2013-05-20 10:21:44.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
sunday_test_ = "C:\\TxDOT\\Scratch\\sunday_test.xlsx\\sunday_test$"
Scratch__2_ = "C:\\TxDOT\\Scratch"

# Process: Table to dBASE (multiple)
arcpy.TableToDBASE_conversion("C:\\TxDOT\\Scratch\\sunday_test.xlsx\\sunday_test$", Scratch__2_)

