# ---------------------------------------------------------------------------
# mapperFieldscratch.py
# Created on: 2014-01-02 15:04:33.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
owssvr_ = "C:\\TxDOT\\CountyRoadInventory\\STATUS\\Book1.xlsx\\owssvr$"
STATUS = "C:\\TxDOT\\CountyRoadInventory\\STATUS"

# Process: Table to Table
arcpy.TableToTable_conversion(owssvr_, STATUS, "queriedtable.dbf", "", "Update_Yea \"Update_Yea\" true true false 255 Text 0 0 ,First,#,C:\\TxDOT\\CountyRoadInventory\\STATUS\\Book1.xlsx\\owssvr$,Update Year,-1,-1;County \"County\" true true false 255 Text 0 0 ,First,#,C:\\TxDOT\\CountyRoadInventory\\STATUS\\Book1.xlsx\\owssvr$,County,-1,-1;Needs_Upda \"Needs_Upda\" true true false 2 Short 0 0 ,First,#,C:\\TxDOT\\CountyRoadInventory\\STATUS\\Book1.xlsx\\owssvr$,Needs Update,-1,-1;Inital_Mar \"Inital_Mar\" true true false 2 Short 0 0 ,First,#,C:\\TxDOT\\CountyRoadInventory\\STATUS\\Book1.xlsx\\owssvr$,Inital Markup Complete,-1,-1;Needs_Fiel \"Needs_Fiel\" true true false 2 Short 0 0 ,First,#,C:\\TxDOT\\CountyRoadInventory\\STATUS\\Book1.xlsx\\owssvr$,Needs Field Verification,-1,-1;Data_Colle \"Data_Colle\" true true false 2 Short 0 0 ,First,#,C:\\TxDOT\\CountyRoadInventory\\STATUS\\Book1.xlsx\\owssvr$,Data Collected,-1,-1;Comanche_U \"Comanche_U\" true true false 2 Short 0 0 ,First,#,C:\\TxDOT\\CountyRoadInventory\\STATUS\\Book1.xlsx\\owssvr$,Comanche Updated,-1,-1", "")

