# ---------------------------------------------------------------------------
# mapperFieldscratch2.py
# Created on: 2014-01-03 10:01:45.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
owssvr_ = "C:\\TxDOT\\CountyRoadInventory\\Book1.xlsx\\owssvr$"
Shapefiles = "C:\\TxDOT\\CountyRoadInventory\\TRACKING\\Shapefiles"

# Process: Table to Table
arcpy.TableToTable_conversion(owssvr_, Shapefiles, "queriedtable.dbf", "", "ID \"ID\" true true false 8 Double 6 15 ,First,#;Update_Yea \"Update_Yea\" true true false 255 Text 0 0 ,First,#,C:\\TxDOT\\CountyRoadInventory\\Book1.xlsx\\owssvr$,Update Year,-1,-1;District \"District\" true true false 255 Text 0 0 ,First,#,C:\\TxDOT\\CountyRoadInventory\\Book1.xlsx\\owssvr$,District,-1,-1;County \"County\" true true false 255 Text 0 0 ,First,#,C:\\TxDOT\\CountyRoadInventory\\Book1.xlsx\\owssvr$,County,-1,-1;Status \"Status\" true true false 255 Text 0 0 ,First,#,C:\\TxDOT\\CountyRoadInventory\\Book1.xlsx\\owssvr$,Status,-1,-1", "")

